SyntaxKit - Swift 4 fixes
alehed/SyntaxKit pull request #4
Opened 2017-08-20 23:41 UTC by mort3m

Migrated to Swift 4 for a new project.
Thought it might be useful some others as well. 

Thanks a lot for you contributions & fixes @alehed!

2017-08-21 05:32 UTC, alehed commented
Thanks a lot @mort3m !

This will be merged as soon as the GM Seed comes out. For the meantime you can fix the remaining issues with indentation. As stated in the `.editorconfig` this project uses four spaces for indentation.

2017-08-21 05:38 UTC, alehed requested changes
I can't see if the whitespace diff is from using tabs instead of spaces or just indenting with one space less than usual.

2017-08-21 05:38 UTC, alehed commented on SyntaxKit/AttributedParser.swift
> +		let output = NSMutableAttributedString(string: string, attributes: base)
This should be 8 spaces instead of seven.

2017-08-21 05:38 UTC, alehed commented on SyntaxKit/Parser.swift
> +				let range = result.range(at: Int(index))
Same here (missing space).

2017-08-21 05:38 UTC, alehed commented on SyntaxKit/Theme.swift
> +			if let value = setting.removeValue(forKey: NSAttributedStringKey(rawValue: "foreground")) as? String {
Also a missing space

2017-08-21 05:38 UTC, alehed commented on SyntaxKit/Theme.swift
> +		return attributes[Language.globalScope]?[NSAttributedStringKey.backgroundColor] as? Color ?? Color.white
Another missing space

2017-08-21 05:38 UTC, alehed commented on SyntaxKit/Theme.swift
> +		return attributes[Language.globalScope]?[NSAttributedStringKey.foregroundColor] as? Color ?? Color.black
Here too.

2017-08-21 05:38 UTC, alehed commented on SyntaxKit/Theme.swift
> +			if let value = setting.removeValue(forKey: NSAttributedStringKey(rawValue: "background")) as? String {
Last one

2017-08-21 08:09 UTC, mort3m commented
Alright @alehed, I will take care of it!

2017-08-21 08:35 UTC, alehed requested changes
Two more lines still contain tabs (53 and 57).

2017-08-21 08:58 UTC, alehed approved these changes

2017-08-21 09:03 UTC, alehed commented
Great, thanks! As mentioned, this will be merged as soon as the GM Seed is released by Apple, which is probably going to happen sometime in September.

Unfortunately, there is currently no editor-config plugin that works in Xcode…

2017-09-13 10:46 UTC, merged

2017-09-13 10:47 UTC, alehed commented
@mort3m Thanks a lot for the contribution! 👍